In [3]:
import numpy as np

In [4]:
!pip install numpy

In [5]:
np.__version__

'1.19.5'

1D Array or Vector

In [279]:
a = np.array([1,2,3,4,5,6,7])
a

array([1, 2, 3, 4, 5, 6, 7])

sort กลับหลัง

In [286]:
idx = np.argsort(-a)
a[idx]

array([7, 6, 5, 4, 3, 2, 1])

In [13]:
a[2:5]

array([3, 4, 5])

In [21]:
a[:6]

array([1, 2, 3, 4, 5, 6])

2D Array or Matrix

In [168]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
a[0]

array([1, 2, 3])

In [36]:
L = [[1,2,3],[4,5,6],[7,8,9]]
L[0]

[1, 2, 3]

In [16]:
L[2:5]

[3, 4, 5]

In [23]:
a[3:]

array([4, 5, 6, 7])

In [24]:
np.size(a)

7

In [26]:
a[a[1]]

3

In [27]:
L[L[2]]

4

In [28]:
np.shape(a)

(7,)

In [29]:
a = a.reshape(1,7)
np.shape(a)

(1, 7)

In [30]:
a[0,0]

1

In [37]:
L[0][0]

1

In [41]:
a[1:]

array([[4, 5, 6],
       [7, 8, 9]])

In [49]:
a[1,:]

array([[1, 2, 3],
       [0, 0, 0],
       [7, 8, 9]])

In [171]:
a[:,-1]=0
a

array([[1, 2, 0],
       [4, 5, 0],
       [7, 8, 0]])

In [45]:
L[:][0]

[1, 2, 3]

In [75]:
a[0:1,:]=1
a

array([[1, 1, 1],
       [4, 5, 6],
       [7, 8, 9]])

In [61]:
np.size(a,1)

3

In [62]:
a.ndim

2

In [63]:
a.shape

(3, 3)

In [76]:
np_mix_matrix = np.array([['one',2],['three',4],['five',6]])
np_mix_matrix

array([['one', '2'],
       ['three', '4'],
       ['five', '6']], dtype='<U5')

In [77]:
a = np.array(np_mix_matrix[:,1], dtype=int)
a

array([2, 4, 6])

In [78]:
a = np.zeros((2,2))
a

array([[0., 0.],
       [0., 0.]])

In [99]:
a = np.ones((3,3))*3
a

array([[3., 3., 3.],
       [3., 3., 3.],
       [3., 3., 3.]])

In [100]:
a = np.full((4,4),2)
a

array([[2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2],
       [2, 2, 2, 2]])

In [102]:
d = np.eye(4)*4
d

array([[4., 0., 0., 0.],
       [0., 4., 0., 0.],
       [0., 0., 4., 0.],
       [0., 0., 0., 4.]])

In [112]:
np.matmul(a,d)

array([[8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.],
       [8., 8., 8., 8.]])

In [110]:
a*d

array([[8., 0., 0., 0.],
       [0., 8., 0., 0.],
       [0., 0., 8., 0.],
       [0., 0., 0., 8.]])

sqrt ราก

In [107]:
np.sqrt(np.full((2,2),9))

array([[3., 3.],
       [3., 3.]])

empty จองที่

In [108]:
np.empty([5,5])

array([[4.68929361e-310, 0.00000000e+000, 6.94725299e-310,
        6.94725299e-310, 6.94725293e-310],
       [6.94725871e-310, 6.94730768e-310, 6.94730770e-310,
        6.94730781e-310, 6.94730781e-310],
       [6.94725847e-310, 6.94730766e-310, 6.94730768e-310,
        6.94730768e-310, 6.94730782e-310],
       [6.94730782e-310, 6.94725299e-310, 6.94730679e-310,
        6.94725581e-310, 6.94730782e-310],
       [6.94725299e-310, 6.94730780e-310, 6.94730778e-310,
        6.94725307e-310, 1.02765654e-321]])

In [113]:
np.sqrt(a)

array([[1.41421356, 1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.41421356, 1.41421356],
       [1.41421356, 1.41421356, 1.41421356, 1.41421356]])

เลขที่สุ่มออกมาจะอยู่ในช่วง 0-1

In [116]:
np.random.rand()

0.6980457582380296

In [125]:
[np.round(np.random.rand()*10) for item in range(10)]

[1.0, 3.0, 5.0, 0.0, 9.0, 2.0, 3.0, 10.0, 7.0, 2.0]

In [148]:
np.random.seed = 1
[np.round(np.random.randint(5)) for item in range(10)]

[4, 3, 0, 3, 0, 4, 0, 0, 3, 4]

In [151]:
np.random.rand(5,5)*10

array([[7.69207154, 1.91471831, 3.06851218, 8.16808209, 3.79700393],
       [3.14823694, 7.83813042, 7.5030402 , 4.15423979, 9.30127476],
       [0.11786456, 6.29521557, 9.02556528, 4.58564505, 1.91128835],
       [5.36529764, 5.6962471 , 2.97872332, 8.63595154, 1.56970478],
       [0.78606556, 3.17342117, 4.2956841 , 6.2634843 , 7.12039361]])

In [155]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,10)

array([ 7, 10,  7,  7,  1,  1,  6,  2,  1,  4])

replace=False ไม่เอาค่าซ้ำ

In [156]:
a = [1,2,3,4,5,6,7,8,9,10]
np.random.choice(a,10, replace=False)

array([ 8,  3,  6,  4,  9, 10,  7,  1,  5,  2])

In [159]:
np_matrix = np.round(np.random.rand(5,5))
np_matrix

array([[0., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 1., 0.],
       [1., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0.]])

In [161]:
idx_choose = np.random.choice(100,3, replace=False)
idx_choose

array([52, 39, 50])

In [165]:
idx_choose = np.random.choice(1000,100, replace=False)
idx_choose

array([745, 310, 276, 435, 582, 391,   3, 608, 425, 740, 914, 956, 401,
       503, 407, 156, 777,  51, 433, 919, 863, 983, 763, 928, 110, 181,
       496, 823, 204, 640, 975,  59, 909, 564, 997,  37,  81, 833,  76,
        67, 162, 894, 887, 970, 348, 364, 861, 505, 677, 473, 482, 770,
        46,  75, 842, 475, 328,  71, 890, 160, 998, 272, 918, 787,  24,
       319, 886, 903, 168, 962, 963, 610, 300, 632, 381, 738, 799, 338,
       419, 925, 672, 111, 344, 469, 203, 707, 579, 661, 812, 457, 716,
       838, 724, 474, 870,  78, 513,   7, 720, 584])

# Ex 2

In [300]:
np_matrix = np.random.rand(10,5)
np_matrix[:,-1]= np.round(np_matrix[:,-1])
np_matrix

array([[0.24504442, 0.55351506, 0.68912892, 0.65935992, 0.        ],
       [0.63175161, 0.50666034, 0.04612819, 0.79530543, 0.        ],
       [0.68244408, 0.31297896, 0.75621556, 0.32307105, 1.        ],
       [0.82730203, 0.70555559, 0.82003415, 0.30714055, 1.        ],
       [0.20493593, 0.56507126, 0.70890388, 0.37385318, 1.        ],
       [0.67426456, 0.90726129, 0.75570253, 0.57888719, 0.        ],
       [0.17410051, 0.95262525, 0.3266766 , 0.41070036, 0.        ],
       [0.42214604, 0.2530167 , 0.22819957, 0.60935309, 0.        ],
       [0.08836699, 0.54028102, 0.23527525, 0.03562395, 0.        ],
       [0.83705886, 0.89965407, 0.05929711, 0.58866287, 0.        ]])

In [304]:
np_matrix = np.random.randint(3,size = (5,5))
np_matrix

array([[1, 1, 1, 1, 1],
       [0, 1, 1, 2, 0],
       [2, 1, 1, 1, 1],
       [0, 0, 2, 1, 0],
       [0, 1, 1, 0, 2]])

In [195]:
row,column = np.where(np_matrix == 2)
[(row[i],column[i]) for i in range (len(row))]

[(1, 0), (1, 2), (2, 1), (2, 3), (2, 4), (3, 1)]

# Ex 3

In [309]:
idx = [1,2,3,4,5]
np_matrix[len(idx)-1:] #เพราะใน idx มี index ถึงแค่ 4

array([[0, 1, 1, 0, 2]])

seed แบบใหม่ np.random.RandomState(SEEDที่)

In [246]:
rng = np.random.RandomState(0)
np_matrix = rng.randint(3,size = (5,5))
np_matrix

array([[0, 1, 0, 1, 1],
       [2, 0, 2, 0, 0],
       [0, 2, 1, 2, 2],
       [0, 1, 1, 1, 1],
       [0, 1, 0, 0, 1]])

In [247]:
np_matrix = np.delete(np_matrix,[1,1],0)
np_matrix

array([[0, 1, 0, 1, 1],
       [0, 2, 1, 2, 2],
       [0, 1, 1, 1, 1],
       [0, 1, 0, 0, 1]])

In [248]:
np_matrix = np.random.randint(10,size = (5,5))
np_matrix

array([[2, 4, 1, 1, 0],
       [0, 4, 3, 6, 9],
       [5, 2, 2, 8, 2],
       [9, 2, 9, 0, 1],
       [3, 8, 8, 5, 4]])

In [249]:
result = (np_matrix == 2)
result

array([[ True, False, False, False, False],
       [False, False, False, False, False],
       [False,  True,  True, False,  True],
       [False,  True, False, False, False],
       [False, False, False, False, False]])

In [250]:
np_matrix[result] = 99
np_matrix

array([[99,  4,  1,  1,  0],
       [ 0,  4,  3,  6,  9],
       [ 5, 99, 99,  8, 99],
       [ 9, 99,  9,  0,  1],
       [ 3,  8,  8,  5,  4]])

# Ex 4

In [311]:
np_matrix = np.random.randint(10,size = (10,5))
np_matrix

array([[3, 5, 2, 2, 7],
       [9, 5, 4, 7, 5],
       [6, 6, 7, 4, 5],
       [5, 6, 8, 0, 2],
       [2, 0, 3, 0, 4],
       [8, 7, 2, 6, 8],
       [9, 3, 6, 6, 2],
       [3, 0, 2, 4, 8],
       [8, 2, 0, 6, 4],
       [4, 5, 3, 6, 9]])

In [314]:
np_vector = np.random.randint(2,size = 10)
np_vector

array([1, 1, 0, 1, 0, 1, 0, 0, 0, 0])

In [315]:
np_matrix[np.where(np_vector == 0)]

array([[6, 6, 7, 4, 5],
       [2, 0, 3, 0, 4],
       [9, 3, 6, 6, 2],
       [3, 0, 2, 4, 8],
       [8, 2, 0, 6, 4],
       [4, 5, 3, 6, 9]])

In [316]:
np_matrix[np.where(np_vector == 1)]

array([[3, 5, 2, 2, 7],
       [9, 5, 4, 7, 5],
       [5, 6, 8, 0, 2],
       [8, 7, 2, 6, 8]])